version: "3.8"

volumes:
  db:

services:
  mysqldb:
    image: mysql:8.0.30
    ports:
      - "3306:3306" #<local-port>:<container-port>

    environment:
      - MYSQL_DATABASE=jenkins
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Iameden321+
      - MYSQL_ROOT_PASSWORD=Iameden321+

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
      - db:/var/lib/mysql

    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - "9191:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306