version: "3.8"

volumes:
  db:

services:
  mysqldb:
    image: mysql:8.0.30
    ports:
      - "3307:3306" #<local-port>:<container-port>
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=jenkins
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=Iameden321+
      - MYSQL_ROOT_PASSWORD=Iameden321+
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
      - db:/var/lib/mysql

    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysqldb:mysql
    ports:
      - "9191:80"
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306