version: "15.1"

services:
  postgres:
    container_name: my_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped

  app:
    links:
      - 'postgres'
    build: .
    depends_on:
      - postgres
    restart: always
    ports:
      - "8080:8080" #<local-port>:<container-port>
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    stdin_open: true
    tty: true

volumes:
  postgres:
  app: