version: "3.8"

volumes:
  db:

services:
  mysqldb:
    image: mysql:8.0.30
    ports:
      - "3306:3306" #<local-port>:<container-port>

    environment:
      - MYSQL_DATABASE=jenkins
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Iameden321+
      - MYSQL_ROOT_PASSWORD=Iameden321+

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
      - db:/var/lib/mysql

    restart: unless-stopped
  app:
    depends_on:
      - mysqldb
    image: spring-boot-app
    restart: always
    ports:
      - "8080:8080" #<local-port>:<container-port>
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/jenkins?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Iameden321+
    stdin_open: true
    tty: true